apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"monitoring"}}
  creationTimestamp: "2026-03-31T04:27:48Z"
  labels:
    kubernetes.io/metadata.name: monitoring
  name: monitoring
  resourceVersion: "8953"
  uid: 8c0cc7ac-72f7-48df-9e4a-60c8c2447341
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
